apiVersion: v1
kind: Secret
metadata:
  name: app-rabbitmq-secret
data:
  RABBITMQ_URL: YW1xcDovL2FkbWluOmFkbWluQHJhYmJpdG1xLnJhYmJpdG1xLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rabbitmq
  labels:
    app: app-rabbitmq
spec:
  selector:
    matchLabels:
      app: app-rabbitmq
  template:
    metadata:
      labels:
        app: app-rabbitmq
    spec:
      containers:
      - name: app-rabbitmq
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["watch"]
        args: ["echo"]
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-rabbitmq-scale
spec:
  scaleTargetRef:
    name: app-rabbitmq
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount:  0 # Optional. Default: 0
  maxReplicaCount: 5 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: queue_number
        mode: QueueLength
        value: "1"
      authenticationRef:
        name: app-rabbitmq-trigger
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: app-rabbitmq-trigger
spec:
  secretTargetRef:
    - parameter: host
      name: app-rabbitmq-secret
      key: RABBITMQ_URL
---