
apiVersion: v1
kind: Secret
metadata:
  name: nodejs-producer-worker-secret
data:
  MESSAGE_QUEUE: YW1xcDovL2FkbWluOmFkbWluQHJhYmJpdG1xLnJhYmJpdG1xLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-producer-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-producer-worker
  template:
    metadata:
      labels:
        app: nodejs-producer-worker
    spec:
      containers: 
      - name: nodejs-producer-worker
        image: pedroarapua/nodejs-rabbitmq:latest
        command: ["npm"]
        args: ["run", "producer"]
        envFrom:
          - secretRef:
              name: nodejs-producer-worker-secret
